import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-gradient-to-br from-blue-600 to-[#00c6e8] p-4 w-full'>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
